name: CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set token secret
        uses: bariscanyilmaz/paste-secret@v1
        with:
          secrets: >
            [{"filename":"appsettings.json","keys":[{"key":"BotToken","value":"${{secrets.BotToken}}"},{"key":"HostAddress","value":"${{ secrets.HostAddress }}"},{"key":"Uri","value":"${{ secrets.Uri }}"}]}]
      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ytu-yemekhane-telegram-bot" #Must be unique in Heroku
          heroku_email: ${{secrets.EMAIL}}
          usedocker: true
