name: CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: jwsi/secret-parser@v1
        with:
          filename: appsettings.json
          secret-name: BotToken
          secret-value: ${{ secrets.BotToken }}
      - name: Build and deploy the Docker image
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ytuyemekhane-telegram-bot
        run: |
          docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME